apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: default
data:
  config.yaml: |
    rules:
      - seriesQuery: 'kafka_consumergroup_lag'
        seriesFilters: []
        resources:
          overrides:
            kubernetes_namespace: {resource: "namespace"}
            kubernetes_pod_name: {resource: "pod"}
        name:
          matches: "kafka_consumergroup_lag"
          as: "kafka_consumergroup_lag"
        metricsQuery: 'avg_over_time(kafka_consumergroup_lag{topic="topic0001",consumergroup="group0001"}[1m])'
